server:
  port: 91

datasource:
  host: "localhost:3306"
  user: "root"
  pass: "12345"
  dbname: "sgp_access_info_svc"

paths:
  getDataAuthLogin: "/v1/sgp-access-logic-svc/getDataAuthLogin"
  createPersonalInfo: "/v1/sgp-access-logic-svc/createPersonalInfo"
  updatePersonalInfo: "/v1/sgp-access-logic-svc/updatePersonalInfo"

app-properties:
  getComorbidity:
    idStatusActive: 1
    idStatusInactive: 2